apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cosign-cli-2-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cosign-cli-2-2
    app.kubernetes.io/part-of: cli-1-0-gamma
  name: cosign-cli-2-2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cosign-cli-2-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cosign-cli-2-2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/cosign-cli-2-2@sha256:59f8dc877991c9ad6a1867c6cdd7be37296ee958cb6e2f124123161821dc518f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
