apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gitsign-cli-0-8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitsign-cli-0-8
    app.kubernetes.io/part-of: cli-1-0-gamma
  name: gitsign-cli-0-8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: gitsign-cli-0-8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: gitsign-cli-0-8
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/gitsign-cli-0-8@sha256:7a72c335bd9f0089e7fceecb8a619b493fdbb727b7feebae4b3f57241b1dfb26
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
