apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gitsign-cli-0-8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitsign-cli-0-8
    app.kubernetes.io/part-of: cli-1-0-gamma
  name: gitsign-cli-0-8
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: gitsign-cli-0-8
status:
  loadBalancer: {}
