apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cosign-cli-2-2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/cosign-cli-2-2@sha256:b88dad968eb12e44f9ff3b3965240f8e2818e1182abc79b8be6610451aff5114
        name: container-image
        resources: {}
status: {}
