apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cosign-cli-2-2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/cosign-cli-2-2@sha256:151f4a1e721b644bafe47bf5bfb8844ff27b95ca098cc37f3f6cbedcda79a897
        name: container-image
        resources: {}
status: {}
