apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cosign-cli-2-2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/cosign-cli-2-2@sha256:465bcd8326b1322bb48129a6e2885bc40660c37fbaf519e8c84642e62a917e70
        name: container-image
        resources: {}
status: {}
