apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cosign-cli-2-2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/cosign-cli-2-2@sha256:dbb6779913641cb17f881d24a640bd4966de2d98c7104f43c2c9744d23025f94
        name: container-image
        resources: {}
status: {}
