apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gitsign-cli-0-8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/gitsign-cli-0-8@sha256:071ba3450607642f2bd576a1e6a55f68e069c0b5dc938903887ab538af1bd8a2
        name: container-image
        resources: {}
status: {}
