apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gitsign-cli-0-8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/gitsign-cli-0-8@sha256:da8157ebe2fe3f9e05f18328b4808351708f4aa184f6ed985ef08ed449fc9596
        name: container-image
        resources: {}
status: {}
