apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gitsign-cli-0-8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/gitsign-cli-0-8@sha256:b8fae228a3e6dd53bfae8f23d44c8e08b4997a62f429f416401657fd54024d83
        name: container-image
        resources: {}
status: {}
