apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gitsign-cli-0-8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/gitsign-cli-0-8@sha256:7a72c335bd9f0089e7fceecb8a619b493fdbb727b7feebae4b3f57241b1dfb26
        name: container-image
        resources: {}
status: {}
