apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gitsign-cli-0-8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitsign-cli-0-8
    app.kubernetes.io/part-of: cli-1-0-gamma
  name: gitsign-cli-0-8mqov
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gitsign-cli-0-8
    weight: 100
status: {}
