apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-cli-1-3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/rekor-cli-1-3@sha256:9f5027e94cb40c8e6ed7e4c743abb45879ff0403c39ab227bdf3c67ca379dcca
        name: container-image
        resources: {}
status: {}
