apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-cli-1-3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/rekor-cli-1-3@sha256:786e90a48b616d4a8b9c4509a757fcd01b36b5088bf07f23ba1d5ed9c1d681f1
        name: container-image
        resources: {}
status: {}
