apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rekor-cli-1-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rekor-cli-1-3
    app.kubernetes.io/part-of: cli-1-0-gamma
  name: rekor-cli-1-3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rekor-cli-1-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rekor-cli-1-3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/rekor-cli-1-3@sha256:d7488929c3cf937242e9505e448c59f7466f600cb2257ce3c441e8d7b3b7b7d7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
